# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-24 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=300)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
