# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181225_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='search_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
